# Generated by Django 3.0.8 on 2020-07-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='college_details',
            fields=[
                ('Eamcet_Code', models.CharField(blank=True, max_length=6, primary_key=True, serialize=False)),
                ('College_Name', models.CharField(blank=True, max_length=100)),
                ('District', models.CharField(blank=True, max_length=20)),
                ('Place', models.CharField(blank=True, max_length=30)),
                ('Contact_No', models.CharField(max_length=10, null=True)),
                ('Website', models.URLField(null=True)),
                ('College_Type', models.CharField(blank=True, max_length=5, null=True)),
                ('Coed', models.CharField(blank=True, max_length=5, null=True)),
                ('Size', models.CharField(blank=True, max_length=5, null=True)),
                ('Academics_Quality', models.CharField(blank=True, max_length=5, null=True)),
                ('Placement_Rating', models.CharField(blank=True, max_length=5, null=True)),
                ('Sports', models.CharField(blank=True, max_length=5, null=True)),
                ('Hostel_B', models.CharField(blank=True, max_length=5, null=True)),
                ('Hostel_G', models.CharField(blank=True, max_length=5, null=True)),
                ('Bus_Facility', models.CharField(blank=True, max_length=5, null=True)),
                ('Clubs', models.CharField(blank=True, max_length=5, null=True)),
                ('Medical_Care', models.CharField(blank=True, max_length=5, null=True)),
                ('NIRF', models.CharField(blank=True, max_length=5, null=True)),
                ('NAAC', models.CharField(max_length=4, null=True)),
                ('NBA', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
