# Generated by Django 3.0.8 on 2020-07-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cutoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eamcet_Code', models.CharField(max_length=6, null=True)),
                ('Course_Code', models.CharField(blank=True, max_length=3)),
                ('Region', models.CharField(blank=True, max_length=3)),
                ('District', models.CharField(blank=True, max_length=20)),
                ('Place', models.CharField(blank=True, max_length=30)),
                ('ocb', models.CharField(blank=True, max_length=10, null=True)),
                ('ocg', models.CharField(blank=True, max_length=10, null=True)),
                ('scb', models.CharField(blank=True, max_length=10, null=True)),
                ('scg', models.CharField(blank=True, max_length=10, null=True)),
                ('stb', models.CharField(blank=True, max_length=10, null=True)),
                ('stg', models.CharField(blank=True, max_length=10, null=True)),
                ('bcab', models.CharField(blank=True, max_length=10, null=True)),
                ('bcag', models.CharField(blank=True, max_length=10, null=True)),
                ('bcbb', models.CharField(blank=True, max_length=10, null=True)),
                ('bcbg', models.CharField(blank=True, max_length=10, null=True)),
                ('bccb', models.CharField(blank=True, max_length=10, null=True)),
                ('bccg', models.CharField(blank=True, max_length=10, null=True)),
                ('bcdb', models.CharField(blank=True, max_length=10, null=True)),
                ('bcdg', models.CharField(blank=True, max_length=10, null=True)),
                ('bceb', models.CharField(blank=True, max_length=10, null=True)),
                ('bceg', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
